const NavigationRoutes = {
  AUTH_STACK: {
    LOGIN: 'LOGIN_SCREEN',
  },
  APP_STACK: {
    BOTTOM_TABS: 'BOTTOM_TABS',
    HOME: 'HOME_SCREEN',
    PROFILE: 'PROFILE',
    SCAN: 'SCAN',
    VIDEO_PLAYER: 'VIDEO_PLAYER',
    ZOOM:"ZOOM",
    COURSES:'COURSES_SCREEN',
    COURSE_DETAIL:'COURSE_DETAIL_SCREEN',
    CLASS:'CLASS_SCREEN',
    LECTURE:'LECTURE_SCREEN',
    ANNOUNCEMENT:'ANNOUNCEMENT_SCREEN',
    QUIZ_RESULT:'QUIZ_RESULT_SCREEN',
    LECTURE_DETAIL:'LECTURE_DETAIL_SCREEN',
    PERSONAL_INFORMATION:'PERSONAL_INFORMATION_SCREEN',
    REPORT_ISSUE:'REPORT_ISSUE_SCREEN',
    SESSIONS:'SESSIONS_SCREEN',
    NOTIFICATION:'NOTIFICATION_SCREEN',
    FAQS:'FAQS_SCREEN',
    ID_CARD:'ID_CARD_SCREEN',
    NOTES:'NOTES',
    WEB_VIEW:'WEBVIEW',
    MESSAGES:'MESSAGES',
    ALL_LECTURES:'ALL_LECTURES'
  },
};

export default NavigationRoutes;
